### ISSUE TITLE
typo in english hints

### ISSUE THREAD

**Issue by DahliaSR** [CheckiO-Missions/checkio-task-three-words#10]
**File:** checkio-task-three-words/hints/bryukh.html  
Line 21: 
> To distinguish **_betwee_** words and numbers, use

should read as:
> To distinguish **_between_** words and numbers, use

**Comment by oduvan** [comment]
you can change it right through the github interface.

That creates a pull request automatically

**Comment by oduvan** [comment]
Thanks for the report

**Comment by DahliaSR** [comment]
@oduvan 
 > you can change it right through the github interface.
 > That creates a pull request automatically

Thx for the hint, will do it like this the next time!
