### ISSUE TITLE
English hint is not clear enough.

### ISSUE THREAD

**Issue by diegueus9** [CheckiO-Missions/checkio-task-three-words#8]
In the file hints/bryukh.html in line 24 says:

**Because words contain only letter words and numbers one method will be enough to solve this mission.**

IMHO, this is not clear enough to understand your hint.

**Comment by Bryukh** [comment]
You can add your own hints as an separate files in Hints folder.

**Comment by diegueus9** [comment]
Right, I supposed that, but I mean that I was translating that sentence to spanish but is doesn't make sense. Perhaps it's something like:

Because words contain only letters and numbers one method will be enough to solve this mission. ?

**Comment by Bryukh** [comment]
Our hints were checked by native american speaker. And letter words != letters. I wanted to say that words (sequence of symbols) are consist only by letters (without numbers as 3rd or 2nd).
